### ISSUE TITLE
Get functional tests fully running

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/rules_conditional#1]
Many do already work, but not all:

163 passes, 4 fails, 0 exceptions, and 26 debug messages.

User Interface

- FAIL: Dependent plugin is unavailable to add.
- FAIL: Single plugins cannot be added more than once.

Framework / testFluentInterface

- FAIL: Fluent interface adds action to the active element.
- FAIL: Fluent interface does not add action to a previously active element.

**Comment by argiepiano** [comment]
Hey @indigoxela. 

I looked into the 2 failures in `RulesConditionalPluginUI`. The reason for the failures is that the link to add a dependent element, which should not be shown, ends up being shown. The problem is generated by the fact that the operations in Backdrop's Rules are placed under the key `['data']` as per this [commit](https://github.com/backdrop-contrib/rules/commit/136b53be280f40160d4f06b88cb0a52c2d4b7f2f) from 3 years ago. This was done so that the operations could be placed in a dropbutton.

So, the solution is to modify `RulesConditionalPluginUI` to unset the link from the correct array path. PR coming. 

I will look into the other 2 failures later.

**Comment by argiepiano** [comment]
OK, the other 2 failures are fixed. The issue was that the test was trying this:
```php
count((array) $actions1->elements())
```
And since the method elements() returns a `RecursiveIteratorIterator` object, you can't cast it into an array. You could use just `count($actions1->elements())` which is what D7 uses, but that gets flagged by the linter (probably why you changed it). It still works despite the linting. The better way is  `iterator_count($actions1->elements())`, which is what I did in the PR.

**Comment by indigoxela** [comment]
@argiepiano awesome! Thank you so much for your PR and helpful explanations. :heart:
